### PR TITLE
Soloud cmake

### PR DESCRIPTION
**Pull request by valid-ptr**
CMake build system added as alternative to genie.lua (not every backend included).
SDL2 compilation fix included

KOS

### CODE REVIEW

**Comment by Itaros** [comment]
What happened to src/backend/sdl2_static/soloud_sdl2_static.cpp ?

**Comment by valid-ptr** [comment]
SDL2's header should be included with

`#include <SDL2/SDL.h>`

with a proper compiler definitions.


This solution was strange:
```
#if defined(_MSC_VER)
    #include "SDL.h"
#else
    #include "SDL2/SDL.h"
#endif
```

**Comment by Itaros** [comment]
> 
> 
> SDL2's header should be included with
> 
> `#include <SDL2/SDL.h>`
> 
> with a proper compiler definitions.
> 
> This solution was strange:
> 
> ```
> #if defined(_MSC_VER)
>     #include "SDL.h"
> #else
>     #include "SDL2/SDL.h"
> #endif
> ```

As much as I would love to have cmake natively for soloud I think those changes should be outside of cmake introduction as it would break all the things(but I haven't used SoLoud with sdl at all and therefore don't have a clue).
@jarikomppa What is your stance on this one? ^_^

**Comment by valid-ptr** [comment]
I don't think it would break **all** the things)

There is FindSDL2.cmake (original from Kitware) with

```
FIND_PATH(SDL2_INCLUDE_DIR SDL2/SDL.h
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES include
	PATHS ${SDL2_SEARCH_PATHS}
)
```

If it would break builds with genie.lua, genie's configuration must be fixed.
Othewise, `cmake build' will give compilation errors.

**Comment by Itaros** [comment]
Yeap, by all the things I was referring to all the configurations genie could generate.

**Comment by jarikomppa** [comment]
Ufff. I really don't know. I personally don't like cmake, even though I can see that some people might want to use it. I definitely don't want to have to maintain cmake support.

As for sdl include paths, I'm pretty sure the <> vs "" change is fine. On windows (where I generally develop) these tend to be synonyms as libraries are installed wherever, whereas in *nix sdl is usually in a well defined place and <> is the (more) correct choice there.

I'm not saying no to this change in general as of yet, I'll have to think about it.

**Comment by jarikomppa** [comment]
Could you make directory "contrib" and move the cmake file there? I think that would work.

**Comment by valid-ptr** [comment]
See #192

**Pull request closed without merging**
