### PR TITLE
Add PS Vita support with vitasdk

### PR DESCRIPTION
**Pull request by xyzz**
This adds support for PS Vita, for use with the homebrew sdk: http://vitasdk.org/

### CODE REVIEW

**Comment by jarikomppa** [comment]
Is this legal? Seems like it's skirting NDA territory..?

**Comment by xyzz** [comment]
This is for homebrew SDK, not official Sony SDK (I don't know if it will work on the official SDK). I have never signed any sort of NDA with Sony.

**Comment by jarikomppa** [comment]
I'd be more comfortable merging this if you renamed it to VitaHomebrew or something. As it is, it looks like it might be related to the official SDK.

**Comment by xyzz** [comment]
Ok, changed as per your suggestion.

**Comment by jarikomppa** [comment]
Wavstream seems to be #if 0'd out?

**Comment by xyzz** [comment]
My bad, I had to #if 0 it to get it to compile and accidentally committed. Fixed now + rebased on top of master.

**Pull request merged**
