### PR TITLE
added support for FILE* in the constructor of SoLoud::DiskFile

### PR DESCRIPTION
**Pull request by brightening-eyes**
this is the SoLoud::File with support for FILE* in the constructor

### CODE REVIEW

**Comment by neilogd** [comment]
It looks like the has the wrong line endings as the diff is screwed up and basically just replaced the whole file.

-----Original Message-----

**Comment by neilogd** [comment]
Also I just noticed that the mFileHandle is public. You can do this already by constructing a DiskFile and assigning it manually. An additional constructor is only really syntactic sugar.

**Comment by brightening-eyes** [comment]
i've added PhysfsFile class based on SoLoud::File, this is in a  seprat header and source

**Comment by brightening-eyes** [comment]
@neilogd
that was public previously, now i've made them private

**Comment by brightening-eyes** [comment]
this is because of my text editor wordpad, sorry for that
i'm using it because my screen reader works well with it

**Comment by jarikomppa** [comment]
Hi, sorry for the delay in reacting to this.

1. I think the FILE * ctor is a good idea - everything is public in SoLoud by convention, and one simple ctor doesn't really bloat things too much.

2. The physfs interface, since it's separate and thus doesn't require one to use physfs to link to soloud is a good idea.. need to figure out how to ignore it in DLL builds though. Perhaps there needs to be some 'extras' directory for stuff like this?

3. Like @neilogd noted, the diffs are not diffs, it seems to be replacing the whole file(s), which makes comparing changes rather difficult.

4. I'd prefer the physfs addition to be a separate pull request - many small changes are better than one big one

5. Remember to add yourself to the AUTHORS file.

**Pull request closed without merging**
