### PR TITLE
Remove *_set3dProcessing from C-api to make Soloud compile.

### PR DESCRIPTION
**Pull request by sammalt**
Apparently those methods were removed earlier. Remove from C API as well.

### CODE REVIEW

**Comment by vinjn** [comment]
@jarikomppa please take a look

**Comment by jarikomppa** [comment]
These are auto-generated, pushing every version to git would create quite a
bit of noise.

**Comment by vinjn** [comment]
I see, however the current C API is not compilable.
And this PR tries to fix the issue.

**Comment by jarikomppa** [comment]
Yes, it does, and since it may be useful to someone, I haven't closed it.

**Pull request closed without merging**
